### ISSUE TITLE
Review storage of sensitive values in TFState var and outputting in logs

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/tfoperatorbridge#21]
Currently values, such as keys, are output in the logs and stored in the TF State. 

Removing them from logs is easy, maybe encrypting state stored on the CRD is a way to secure those left in state - that bits a bit more tricky

**Comment by jjcollinge** [comment]
After discussing this; we're tracking this as individual issues:

- Suppress provider logs to avoid leaking secrets #22 
- Encrypt tfstate stored in CRD #45 
- Encrypt sensitive values stored in CRD status #50

**Comment by jjcollinge** [comment]
Closed by #51
