### ISSUE TITLE
Handle ignored errors properly

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/tfoperatorbridge#39]
Let's run some checks for ignored or `_` error cases and ensure they are handled correctly.

**Comment by lawrencegripper** [comment]
Yeah golangci_lint is a must. Config from Azbrowse will check for unhandled errors and other useful bits (dead code etc) https://github.com/lawrencegripper/azbrowse/blob/master/.golangci.toml

**Comment by lawrencegripper** [comment]
Might try and take this one on tonight unless anyone objects?

**Comment by lawrencegripper** [comment]
Done in #42
