### ISSUE TITLE
Settings the `status` fields on a CRD

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/tfoperatorbridge#9]
Inverse of the existing mapping from `applyJson` and `openAPI` spec mapping. 

For any of the TF Schema fields that are `optional` put them in `status` section of CRD.

**Comment by stuartleeks** [comment]
Currently the code expects there to be an `id` property on the Terraform object and in the CRD `status` object.

This was added to unblock other work and provides the placeholder for a proper implementation, but other than that should be removed!
